demo/protected/models/User.php
<?php

class User extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_user':
	 * @var integer $id
	 * @var string $username
	 * @var string $password
	 * @var string $salt
	 * @var string $email
	 * @var string $profile
	 */

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{user}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username', 'required'),
			array('username', 'length', 'max'=>255),
			array('profile', 'safe'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'username' => 'Username',
		);
	}
}

demo/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout = 'column1';

	/**
	 * Displays the front page.
	 */
	public function actionIndex()
	{
		$this->redirect(array('/auth/assignment/index'));
	}

	public function actionChangeLanguage($locale)
	{
		if (in_array($locale, array_keys(Yii::app()->languages)))
			Yii::app()->user->setState('__locale', $locale);

		$this->redirect(array('index', 'language'=>$locale));
	}

	/**
	 * Resets the database for the demo application.
	 */
	public function actionReset()
	{
		/* @var $db CDbConnection */
		$db = Yii::app()->getComponent('db');
		$filename = dirname(__FILE__) . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'schema.sql';
		if (file_exists($filename))
		{
			$schema = file_get_contents($filename);
			$schema = preg_split("/;\s+/", trim($schema, ';'));
			foreach ($schema as $sql)
				$db->createCommand($sql)->execute();
		}
		Yii::app()->user->setFlash('success', 'Demo reset.');
		$this->redirect(array('index'));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error)
		{
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

demo/protected/views/layouts/column1.php
<?php $this->beginContent('/layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

demo/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
	<div class="row">
		<div class="span9">
			<div id="content">
				<?php echo $content; ?>
			</div><!-- content -->
		</div>
		<div class="span3">
			<div id="sidebar">
				<?php if(!Yii::app()->user->isGuest): ?>
					<?php $this->widget('UserMenu'); ?>
				<?php endif; ?>

				<?php $this->widget('TagCloud', array(
					'maxTags'=>Yii::app()->params['tagCloudCount'],
				)); ?>

				<?php $this->widget('RecentComments', array(
					'maxComments'=>Yii::app()->params['recentCommentCount'],
				)); ?>
			</div><!-- sidebar -->
		</div>
	</div>
<?php $this->endContent(); ?>

demo/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/styles.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl; ?>/css/main.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

	<?php Yii::app()->bootstrap->register(); ?>
</head>

<body>

<?php $this->widget('bootstrap.widgets.TbNavbar',array(
	'type'=>'inverse',
	'items'=>array(
		array(
			'class'=>'bootstrap.widgets.TbNav',
			'items'=>array(
				array('label'=>'Download', 'url'=>'http://www.yiiframework.com/extension/auth/'),
				array('label'=>'Fork on GitHub', 'url'=>'https://github.com/Crisu83/yii-auth/'),
				array('label'=>'Reset demo', 'url'=>array('/site/reset'), 'linkOptions'=>array('confirm'=>'Are you sure you want to reset the database?')),
			),
		),
		array(
			'class'=>'LanguageMenu',
			'htmlOptions'=>array('class'=>'pull-right'),
		),
	),
)); ?>

<div class="container" id="page">

	<?php $this->widget('bootstrap.widgets.TbAlert'); ?>

	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?>
	<?php endif?>

	<?php echo $content; ?>

	<hr />

	<div id="footer">
		&copy; Christoffer Niska <?php echo date('Y'); ?> <br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div>

</div>

</body>
</html>

demo/protected/views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
	<?php echo CHtml::encode($message); ?>
</div>